development:
  sessions:
    default:
      database: kc_courses_dev
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: kc_courses_test
      hosts:
        - localhost:27017